
/*
 * Copyright © 1996-2012 by 4system Polska Sp. z o.o.
 * All Rights Reserved. v4
 */

if (typeof(lexicon) != "undefined") {
	lexicon.add("manetka", "Reguluje dopływ mieszanki paliwowej do silnika umożliwiając płynną zmianę obrotów silnika (prędkości jaką nadaje on łodzi). Przyjmuje postać obrotowej tulei umieszczonej na końcówce rumpla silnika (w przypadku silników przyczepnych/zaburtowych; operowanych ręcznie) lub dźwigni (w przypadku sterowania silnikiem za pomocą cięgien; z reguły duże silniki stacjonarne). Manetka pozwala na ustawienie w dwóch skrajnych położeniach: bieg naprzód i bieg wstecz, oraz w neutralnym (luz). Pozwala to na wysprzęglanie obrotów silnika przy zmianie kierunku obrotu silnika (naprzód, wstecz; pędnik w wodzie) i płynną regulację jego prędkości obrotowej.", "");
	lexicon.add("silnik czterosuwowy", "Rodzaj silnika spalinowego, w którym suw pracy następuje co czwarty suw tłoka. Polega to na przemieszczeniu się tłoka w czterech fazach działania: wpływu powietrza lub mieszanki paliwowo-powietrznej, sprężenia, pracy, wydmuchu spalin. Cykl taki obejmuje dwa obroty wału korbowego, czyli silnik czterosuwowy to silnik, którego tłok wykonuje cztery ruchy posuwisto-zwrotne w jednym cyklu roboczym.", "Eksploatacja silników");
	lexicon.add("silnik dwusuwowy", "Rodzaj silnika spalinowego, w którym suw pracy następuje co drugi suw tłoka.  Polega to na przemieszczeniu się tłoka od górnego do dolnego skrajnego położenia (za każdym obrotem wału korbowego). Osiągnąć można w ten sposób wyższą moc jednostkową, niż silniki czterosuwowe (gdzie jeden cykl pracy przypada na dwa obroty wału). Suw ssania i sprężania znany z cyklu czterosuwowego zastąpiony jest tzw. cyklem płukania, przeprowadzanym przez zewnętrzną względem cylindra pompę ładującą.", "Eksploatacja silników");
	lexicon.add("suw pracy", "Jeden z suwów obiegu pracy pracy silnika dwusuwowego, polega na tym, że przed dojściem do górnego martwego położenia tłoka następuje zapłon paliwa, które gwałtownie rozprężając się powoduje ruch tłoka w dół do dolnego skrajnego położenia, w końcowej fazie tego suwu może mieć miejsce początek cyklu płukania (zapoczątkowujący suw sprężania).", "Eksploatacja silników");
	lexicon.add("suw sprężania", "Jeden z suwów obiegu pracy pracy silnika dwusuwowego, polega na tym, że w pierwszej fazie suwu sprężania następuje płukanie przestrzeni roboczej silnika, Wtedy to spaliny powstałe w poprzednim cyklu pracy są wytłaczane przez kanał wydechowy napływającym świeżym ładunkiem.", "Eksploatacja silników");
	lexicon.add("zrywka", "Rodzaj linki umożiwiającej automatyczne zatrzymanie pracy silnika przyczepnego (zaburtowego), przypinanej do wyłącznika silnika (stop) za pomocą miniaturowej klamry, której zerwanie odcina dopływ paliwa do silnika, drugi koniec linki (najczęsciej wykonanej ze spiralnego cięgna przypominającego stary przewód słuchawkowy telefonu stacjonarnego) powinien być wpięty w element odzieży jaką nosi na sobie skipper łodzi (jego ewentualne wypadniięcie za burtę lub poślizgnięcie się na pokładzie spowoduje zatrzymanie pracy silnika).", "Eksploatacja silników");
}
